### ISSUE TITLE
Attempting to use kaiser-ruby produces syntax error from gem

### ISSUE THREAD

**Issue by PanoramicPanda** [marcinruszkiewicz/kaiser-ruby#1]
```
C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': C:/Ruby23/lib/ruby/gems/2.3.0/gems/kaiser-ruby-0.4.2/lib/kaiser_ruby/cli.rb:55: syntax error, unexpected keyword_rescue, expecting keyword_end (SyntaxError)
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/kaiser-ruby-0.4.2/exe/kaiser-ruby:5:in `<top (required)>'
        from C:/Ruby23/bin/kaiser-ruby:22:in `load'
        from C:/Ruby23/bin/kaiser-ruby:22:in `<main>'
```

**Comment by marcinruszkiewicz** [comment]
Hi, it's because of [this](https://bugs.ruby-lang.org/issues/12906) - I'm using Ruby 2.5 everywhere so I'm already used to the goodies, and on older versions it would indeed break like this.

I'll fix it properly some time today when I get a free moment. Thanks!

**Comment by marcinruszkiewicz** [comment]
@PanoramicPanda should be fixed on the newest version of the gem. :)

**Comment by PanoramicPanda** [comment]
Thanks! Worked like a charm. We're locked to 2.3 at the office right now, but now I can make everyone a Rockstar!
